kumuluzee:
  name: transaction-service
  env:
    name: dev
  version: 1.0.0
  server:
    #base-url: http://localhost:8082
    base-url: http://20.124.175.39:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/TransactionDS
      #connection-url: jdbc:postgresql://localhost:5432/lottery-ticket
      #connection-url: jdbc:postgresql://sqlsimplsrecka.postgres.database.azure.com:5432/lottery-ticket
      username: lukaariana
      password:  ${{ secrets.AZURE_CREDENTIALS }}
      #username: dbuser
      #password: postgres
      pool:
        max-size: 4
  dev:
    scan-libraries:
      - transaction-models
      - transaction-services
      - transaction-lib
  openapi-mp:
    ui:
      #specification-server: http://localhost:8082
      specification-server: http://20.124.175.39:8082
    swagger-ui:
      path: /transaction/api-specs/ui
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/TransactionDS
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  metrics:
    web-instrumentation:
      - name: transaction-endpoint
        url-pattern: /v1/transaction/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="SimplSrecka">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="754b7d50-cb52-4b7f-af7f-0a0827e24bef-ls.logit.io"
                                    port="26348" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  broken: false

